### PR TITLE
🐛 Fix breaking issue with revoked passports

### LINKED ISSUE #5: Add handling of revoked passports

### PR DESCRIPTION
**Pull request by acemasterjb**
Fixes #5  .

Changes proposed in this pull request:
- 🐛 Fix issue with revoked passports, use `PassportIssuer` subgraph to filter out passports which are revoked
  - utilises [subgraph](https://thegraph.com/hosted-service/subgraph/nation3/passportissuance) to get list of revoked ids

All changes pass the following tests:

```console
yarn test --strategy=nation3-passport-coop-with-delegations
```

### CODE REVIEW

File: src/strategies/nation3-passport-coop-with-delegations/index.ts [hunk 1]
```diff
@@ -29,28 +32,49 @@ export async function strategy(
...
   );
 
+  const erc721SignerCaller = new Multicaller(network, provider, signerAbi, {
+    blockTag
+  });
+  const erc721OwnerCaller = new Multicaller(network, provider, ownerAbi, {
+    blockTag
+  });
+
+  const passportIssuanceSubgrgraph = "https://api.thegraph.com/subgraphs/name/nation3/passportissuance";
```
Comment (johnmark13) [inline src/strategies/nation3-passport-coop-with-delegations/index.ts:53]: I think that this should be in configuration just because in theory this is a strategy that could be used by other projects, even if that is really unlikely! maybe just the `nation3/passsportissuance` part...

**Review by johnmark13 — COMMENTED** [review]
I love this work, and so fast, evn if I don't think you should move constants around inside another PR just to have them in a neat order. I am only holding off approval because of other comments on the subgraph PR.

File: src/strategies/nation3-passport-coop-with-delegations/index.ts (hunk 1 above)
Comment (aahna-ashina) [inline src/strategies/nation3-passport-coop-with-delegations/index.ts:53]:
```suggestion
  const passportIssuanceSubgraph = "https://api.thegraph.com/subgraphs/name/nation3/passportissuance";
```

**Review by aahna-ashina — APPROVED** [review]
